'use client';
import {useEffect,useState} from 'react';
import {Play,RefreshCw} from 'lucide-react';
import {AdminNav} from '@/app/components/admin-nav';
import {AdminDataLoading} from '@/app/components/admin-data-loading';
import {readAdminCache,writeAdminCache} from '@/lib/admin-client-cache';
import {supabase} from '@/lib/supabase';
import {syncHealthLabel,type SyncHealth} from '@/lib/sync-status';

type Failure={propertyId:string;name:string;month:string};
type Run={id:string;trigger:'cron'|'manual';status:'running'|'success'|'partial'|'failed';started_at:string;finished_at:string|null;property_count:number;completed_count:number;saved_records:number;failure_count:number;failures:Failure[];request_id:string;retry_of:string|null;skipped_count:number;failure_scope:'targets'|'run'};
export default function AdminSyncPage(){
 const cacheKey='/api/admin/sync';
 const [runs,setRuns]=useState<Run[]>([]),[health,setHealth]=useState<SyncHealth>('delayed'),[schedule,setSchedule]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function authHeader(){const {data:{session}}=await supabase!.auth.getSession();if(!session)throw new Error('운영자 로그인이 필요합니다.');return {Authorization:`Bearer ${session.access_token}`};}
 async function load(){if(!supabase)return;setLoading(true);try{const response=await fetch(cacheKey,{headers:await authHeader()}),result=await response.json();if(response.status===401||response.status===403){window.location.assign('/admin/login');return;}if(!response.ok)throw new Error(result.error||'자동수집 상태를 불러오지 못했습니다.');writeAdminCache(cacheKey,result);setRuns(result.runs);setHealth(result.health);setSchedule(result.schedule);setNotice('');}catch(error){setNotice(error instanceof Error?error.message:'자동수집 상태를 불러오지 못했습니다.');}finally{setLoading(false);}}
 useEffect(()=>{const cached=readAdminCache<{runs:Run[];health:SyncHealth;schedule:string}>(cacheKey);if(cached){setRuns(cached.runs);setHealth(cached.health);setSchedule(cached.schedule);}void load();},[]);
 async function execute(url:string,message:string){setBusy(true);setNotice('');try{const response=await fetch(url,{method:'POST',headers:await authHeader(),signal:AbortSignal.timeout(300000)}),result=await response.json();if(!response.ok)throw new Error(result.error||'자동수집을 시작하지 못했습니다.');setNotice(message);await load();}catch(error){setNotice(error instanceof Error?error.message:'자동수집을 시작하지 못했습니다.');await load();}finally{setBusy(false);}}
 const latest=runs[0];
 return <main className="admin-page"><AdminNav active="sync"/><div className="admin-heading"><div><h1>자동수집</h1><p>{schedule}</p></div><div className="heading-actions">{loading&&runs.length>0&&<small className="muted">갱신 중…</small>}<button className="button primary" disabled={busy||health==='running'} onClick={()=>void execute('/api/admin/sync','전체 자동수집을 완료했습니다.')}><Play size={17}/>지금 전체 실행</button></div></div>{notice&&<p className="admin-notice" role="status">{notice}</p>}{loading&&!runs.length?<AdminDataLoading label="자동수집 이력"/>:<><section className="sync-overview"><article className={`panel sync-health ${health}`}><small>최근 전체 실행 상태</small><strong>{syncHealthLabel(health)}</strong><p>{latest?new Date(latest.started_at).toLocaleString('ko-KR'):'아직 실행 기록이 없습니다.'}</p></article><article className="panel"><small>최근 처리 단지</small><strong>{latest?.property_count??0}개</strong><p>완료한 단지·월 {latest?.completed_count??0}건</p></article><article className="panel"><small>최근 반영 거래</small><strong>{latest?.saved_records??0}건</strong><p>실패 {latest?.failure_count??0}건</p></article></section><section className="panel sync-history"><h2>실행 이력</h2>{runs.length?<div className="sync-table"><div className="sync-row sync-head"><span>상태</span><span>방식</span><span>시작·완료</span><span>처리 결과</span><span>추적 ID</span></div>{runs.map(run=><div className="sync-row" id={`run-${run.id}`} key={run.id}><span className={`sync-status ${run.status}`}>{syncHealthLabel(run.status)}</span><span>{run.retry_of?'실패 재시도':run.trigger==='cron'?'예약':'수동'}</span><span>{new Date(run.started_at).toLocaleString('ko-KR')}<br/>{run.finished_at&&new Date(run.finished_at).toLocaleString('ko-KR')}</span><span>{run.saved_records}건 반영 · 실패 {run.failure_count}{run.skipped_count?` · 제외 ${run.skipped_count}`:''}</span><code>{run.request_id}</code>{run.retry_of&&<p>원본 실행: <a href={`#run-${run.retry_of}`}>{run.retry_of.slice(0,8)}</a></p>}{run.failures.length>0&&<div className="sync-failures"><ul>{run.failures.map((failure,index)=><li key={`${failure.propertyId}-${failure.month}-${index}`}>{failure.name} {failure.month||'실행 단계'}</li>)}</ul>{run.failure_scope==='targets'&&<button className="button" disabled={busy||health==='running'} onClick={()=>void execute(`/api/admin/sync/${run.id}/retry`,'실패 대상 재수집을 완료했습니다.')}>{busy?<RefreshCw className="spin" size={15}/>:null}실패 대상만 재시도</button>}</div>}</div>)}</div>:<p className="muted">아직 실행 기록이 없습니다.</p>}</section></>}</main>;
}
